services:
  frutymax:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frutymax-app
    restart: unless-stopped
    ports:
      - "81:81"
    volumes:
      - ./out:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frutymax-network

networks:
  frutymax-network:
    driver: bridge

