services:
  frutymax:
    build:
      context: .
      dockerfile: Dockerfile
    image: frutymax-next:latest
    expose:
      - "3000"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frutymax.rule=Host(`frutymax.exloz.site`)"
      - "traefik.http.routers.frutymax.entrypoints=websecure"
      - "traefik.http.routers.frutymax.tls.certresolver=le"
      - "traefik.http.services.frutymax.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true